### ISSUE TITLE
zccd.csv is missing zip code 22350

### ISSUE THREAD

**Issue by typpo** [OpenSourceActivismTech/us-zipcodes-congress#2]
According to [house.gov](https://ziplook.house.gov/htbin/findrep_house?ZIP5), 22350 maps to the 8th Congressional district in VA.

22350 is present in zzcd_hud.csv

**Comment by jlev** [comment]
Thanks @typpo, this must be one of the new zipcodes since the 2010 Census. According to [zip-codes.com](https://www.zip-codes.com/zip-code/22350/zip-code-22350.asp) it's mostly a botanical preserve, so it might not have enough population to be counted as a ZCTA.

It's present in the HUD file, because they have access to more frequent USPS updates. That file is always going to be more reliable, but it's also license encumbered, so I keep both around.

**Comment by typpo** [comment]
Thanks :)
